  rsaEncrypt.c
rsaEncrypt.obj : error LNK2019: _CRYPTO_malloc_main 함수에서 참조되는 확인할 수 없는 외부 기호
rsaEncrypt.obj : error LNK2019: _CRYPTO_free_main 함수에서 참조되는 확인할 수 없는 외부 기호
rsaEncrypt.obj : error LNK2019: _OPENSSL_init_crypto_main 함수에서 참조되는 확인할 수 없는 외부 기호
rsaEncrypt.obj : error LNK2019: _BIO_new_file_main 함수에서 참조되는 확인할 수 없는 외부 기호
rsaEncrypt.obj : error LNK2019: _BIO_free_main 함수에서 참조되는 확인할 수 없는 외부 기호
rsaEncrypt.obj : error LNK2019: _BIO_write_main 함수에서 참조되는 확인할 수 없는 외부 기호
rsaEncrypt.obj : error LNK2019: _EVP_PKEY_free_main 함수에서 참조되는 확인할 수 없는 외부 기호
rsaEncrypt.obj : error LNK2019: _EVP_PKEY_CTX_new_main 함수에서 참조되는 확인할 수 없는 외부 기호
rsaEncrypt.obj : error LNK2019: _EVP_PKEY_CTX_new_id_main 함수에서 참조되는 확인할 수 없는 외부 기호
rsaEncrypt.obj : error LNK2019: _EVP_PKEY_CTX_free_main 함수에서 참조되는 확인할 수 없는 외부 기호
rsaEncrypt.obj : error LNK2019: _EVP_PKEY_encrypt_init_main 함수에서 참조되는 확인할 수 없는 외부 기호
rsaEncrypt.obj : error LNK2019: _EVP_PKEY_encrypt_main 함수에서 참조되는 확인할 수 없는 외부 기호
rsaEncrypt.obj : error LNK2019: _EVP_PKEY_keygen_init_main 함수에서 참조되는 확인할 수 없는 외부 기호
rsaEncrypt.obj : error LNK2019: _EVP_PKEY_keygen_main 함수에서 참조되는 확인할 수 없는 외부 기호
rsaEncrypt.obj : error LNK2019: _EVP_PKEY_CTX_set_rsa_padding_main 함수에서 참조되는 확인할 수 없는 외부 기호
rsaEncrypt.obj : error LNK2019: _EVP_PKEY_CTX_set_rsa_keygen_bits_main 함수에서 참조되는 확인할 수 없는 외부 기호
rsaEncrypt.obj : error LNK2019: _PEM_write_bio_PrivateKey_main 함수에서 참조되는 확인할 수 없는 외부 기호
rsaEncrypt.obj : error LNK2019: _PEM_write_bio_PUBKEY_main 함수에서 참조되는 확인할 수 없는 외부 기호
rsaEncrypt.obj : error LNK2019: _ERR_print_errors_fp_handleErrors 함수에서 참조되는 확인할 수 없는 외부 기호
C:\Program Files\OpenSSL-Win64\lib\VC\x64\MDd\libcrypto.lib : warning LNK4272: 'x64' 라이브러리 컴퓨터 종류가 'x86' 대상 컴퓨터 종류와 충돌합니다.
C:\Users\geunh\source\repos\RSAProject\x64\Debug\RSAencryptProject.exe : fatal error LNK1120: 19개의 확인할 수 없는 외부 참조입니다.
